### ISSUE TITLE
background color doesn't change

### ISSUE THREAD

**Issue by junhyeokahn** [rhysd/vim-color-spring-night#1]
Hi,
First of all, I really appreciate you effort to build this awesome theme.

However, I downloaded it with vim-plug and its background is black not deep blue.
I guess one of my tmux conf or vimrc may mess it up but I have no idea about it.

I would really appreciate if you can give me some advice.

**Comment by rhysd** [comment]
I guess your environment is 256 colors, not a true colors. In 256 colors, there is no good deep blue color so falling back into black.

To enable true color, you need to use `termguicolors` option with true color-enabled terminal. Please try it.

c.f. https://github.com/vim/vim/issues/993

**Comment by junhyeokahn** [comment]
Thanks for reply :)
I tried solutions on vim #993 but when I try each of them
it returns,
E518 : Unknow option : termguicolors
E355: Unknow option : t_8f
E355: Unknow option : t_8b

My vim version is below,
<img width="838" alt="screen shot 2017-02-20 at 12 20 04 am" src="https://cloud.githubusercontent.com/assets/23005104/23114078/64a6c0ca-f702-11e6-92d1-d4dadced168b.png">

**Comment by rhysd** [comment]
I guess your vim version is old. If `termguicolors` is not available, deep blue color is only available on gVim because of limitation of 256 colors...

**Comment by rhysd** [comment]
`termguicolors` seems to be introduced at Vim 7.4.1799.

https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162

**Comment by junhyeokahn** [comment]
I just reinstall vim with home-brew and it seems working,
Thank you so much. :)
