### ISSUE TITLE
vim-plug deleted packages is not comfortable to read

### ISSUE THREAD

**Issue by robsonpeixoto** [rhysd/vim-color-spring-night#10]
![image](https://user-images.githubusercontent.com/124390/60175978-65a60a80-97eb-11e9-8d3a-2d458300bf92.png)

![image](https://user-images.githubusercontent.com/124390/60176232-1d3b1c80-97ec-11e9-96ef-09487009753d.png)

I really love this theme. I'll open a lot of issues =D

**Comment by rhysd** [comment]
Because I'm not using vim-plug, I'm not getting the point. Could you explain which part is going wrong? If you're ok, pasting the same output with other colorscheme would help me to understand the issue.

**Comment by rhysd** [comment]
In addition, would you like to tell me the output of following command after moving the cursor on the problematic part?

```vim
:echom 'hi<' . synIDattr(synID(line('.'),col('.'),1),'name') . '>trans<' . synIDattr(synID(line('.'),col('.'),0),'name') . '>lo<' . synIDattr(synIDtrans(synID(line('.'),col('.'),1)),'name') . '>'
```

This shows which highlight group is used under the cursor.

**Comment by robsonpeixoto** [comment]
You just need to define a good `Ignore` color.

The output of the command is:
`hi<plugDeleted>trans<plugDeleted>lo<Ignore>`

**Comment by rhysd** [comment]
OK, I understood situation. Let me consider how to handle this.

**Comment by rhysd** [comment]
From `:help :hi`,

> 	Ignore		left blank, hidden

So, current highlighting (show nothing by using the same color as background for foreground) seems correct.
The point is vim-plug is using this highlighting group not to ignore something, but to weaken color. I think `plugDeleted` should be handled individually.

**Comment by rhysd** [comment]
I used the same color as comments for `plugDeleted`. How about this? I did not confirm because I'm not using vim-plug. Please let me know if it is still not comfortable.

**Comment by robsonpeixoto** [comment]
![image](https://user-images.githubusercontent.com/124390/60312242-f4706f80-9930-11e9-92a2-e04744f111f6.png)

Amazing !!!
