### ISSUE TITLE
MatchParen highlight resembles error / warning colors

### ISSUE THREAD

**Issue by jparise** [rhysd/vim-color-spring-night#14]
The `MatchParen` highlight is very close to the colors used for errors and warnings. I often find myself staring at a highlighted matching bracket and then realizing that it's not actually an error.

Would you consider using a different highlight for `MatchParen`?

**Comment by rhysd** [comment]
Thanks. If possible, could you show screenshot?

**Comment by jparise** [comment]
Here's a simple example from a `json` buffer:

<img width="141" alt="Screen Shot 2020-06-02 at 10 46 52 AM" src="https://user-images.githubusercontent.com/10311/83552330-6f85c280-a4be-11ea-8aac-9874620d3013.png">

You can see the matching paren as well as the highlighted syntax error. The colors are inverted (black on red vs. red on black), but the red-ish-ness stands out in both places.

**Comment by rhysd** [comment]
Thanks. I understood the situation.

**Comment by rhysd** [comment]
Now yellow is used for `MatchParen`:

<img width="252" alt="スクリーンショット 2020-07-22 20 52 36" src="https://user-images.githubusercontent.com/823277/88173349-5fd46000-cc5d-11ea-9057-152250154ae9.png">
