### ISSUE TITLE
Background resets when vimrc is sourced

### ISSUE THREAD

**Issue by akinsho** [rhysd/vim-color-spring-night#2]
Hi, thanks for the great theme which I love, the only issue I am having is when I source my vimrc it changes the background to dark but on opening it or using it generally this does not happen. It only occurs when I source it. 

I'm using terminal vim version 8.0
Inside Tmux version 2.3 (the issue occurs regardless of whether I use Tmux)
iTerm 2 build 3.0.14
Installed with Vundler

I've tried removing all display related themes and tinkered with most of my display related setting, below is a section of my vimrc with my display settings

```
if !has('gui_running')
  set term=screen-256color
endif


if has('termguicolors')
  set termguicolors


  " set vim-specific sequences for rgb colors
  "truecolor support in vim
  let &t_8f = "\<esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<esc>[48;2;%lu;%lu;%lum"
endif


colorscheme spring-night
set g:spring_night_high_contrast=['cui']


```
Before:
<img width="1000" alt="screen shot 2017-02-25 at 19 15 30" src="https://cloud.githubusercontent.com/assets/22454918/23334043/dcc9d8a4-fb8e-11e6-8b29-962880018a1d.png">

After:
<img width="621" alt="screen shot 2017-02-25 at 19 11 40" src="https://cloud.githubusercontent.com/assets/22454918/23334030/99e0fc16-fb8e-11e6-96a5-99a2d28a3abb.png">

**Comment by rhysd** [comment]
Thank you for your detailed report. Could you confirm wether the problem occurs or not when using other color scheme? If it occurs with other color scheme also, it may not be the problem of vim-color-spring-night itself.

**Comment by akinsho** [comment]
It seems to only be whilst using the theme, I'm not sure if its my current settings above or whether there is another variable I should set to keep the theme light. I've tried setting background to light but that does not work.

**Comment by rhysd** [comment]
> set g:spring_night_high_contrast=['cui']

The `set` should be `let`. Could you try the fix?

**Comment by rhysd** [comment]
I maybe have found the reason. You should set variable before setting colorscheme.

```
if !has('gui_running')
  set term=screen-256color
endif


if has('termguicolors')
  set termguicolors


  " set vim-specific sequences for rgb colors
  "truecolor support in vim
  let &t_8f = "\<esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<esc>[48;2;%lu;%lu;%lum"
endif

let g:spring_night_high_contrast=['cui']
colorscheme spring-night
```

Please try it.

**Comment by rhysd** [comment]
And 'high contrast' means darker background color. So if you want lighter theme, please try `let g:spring_night_high_contrast=[]`.

**Comment by akinsho** [comment]
Hi, thanks very much I just tried it out and it worked! thanks again for the great theme, maybe you should add a line about implementing the contrast i.e. an example use of the contrast variable
