### ISSUE TITLE
Can you add syntax highlight for SQL?

### ISSUE THREAD

**Issue by atsusta** [rhysd/vim-color-spring-night#3]
Hello, loving and using your awesome color scheme, I have a request for you.
Can you add syntax highlight for _SQL_? (Actually, I'm working as database administrator.)
Basic syntax highlight is available in *.sql files, but it doesn't work when I editing code block in **markdown** files...
I hope the cool colors be obvious in my documents:)

Hope you keep going your great work.
Yours sincerely.

**Comment by rhysd** [comment]
It's not a problem of color scheme. Please add below configuration to your `.vimrc`.

```vim
" Enumerate filetypes you want to highlight in code block in markdown.
" Please be careful because too many items in the list will make highlighting markdown slow.
let g:markdown_fenced_languages = ['sql']
```

And then try to edit your markdown doc.

**Comment by atsusta** [comment]
It works. thanks for your help!
