### ISSUE TITLE
iTerm2 colorscheme

### ISSUE THREAD

**Issue by simaoneves** [rhysd/vim-color-spring-night#5]
This is a great colorscheme! Thanks!
Something that would be great is to have terminal themes aswell, to match Vim.

**Comment by rhysd** [comment]
It would be great to have iTerm2 color theme. I'm using iTerm2 but not configuring color theme. So I'm not sure how to create and need to know that.

**Comment by simaoneves** [comment]
Can https://terminal.sexy help? I believe it exports iTerm2 colorscheme format

**Comment by rhysd** [comment]
The service looks useful. I think I should try :smile:

**Comment by CaryWill** [comment]
@simaoneves @rhysd Try it https://github.com/rhysd/vim-color-spring-night/pull/17

**Comment by rhysd** [comment]
Fixed by #17. Closing. Thank you @CaryWill.

**Comment by simaoneves** [comment]
Wow this is great, many thanks @CaryWill !
