### ISSUE TITLE
I want SignColumn to differ from TabLine

### ISSUE THREAD

**Issue by tyru** [rhysd/vim-color-spring-night#7]
I think it's special case, but I want SignColumn to differ from TabLine.
I'm using [Vim-TabSideBar](https://rbtnn.github.io/vim/) patch, so "tabsidebar" is left of sign column.
The highlight group of tabsidebar is `TabSideBar`, it's linked to `TabLine` at the top of tab page.

![image](https://user-images.githubusercontent.com/48169/48298436-cbfe4700-e500-11e8-90da-ce4e52cc926d.png)

But it's difficult to see sign is appeared, for example, when warning(s) / error(s) of [ALE](https://github.com/w0rp/ale) exist in buffer.

![5859d7fd32d66cffab681eb230592428](https://user-images.githubusercontent.com/48169/48298458-49c25280-e501-11e8-8ef0-264eb5245652.gif)

So now temporarily I changed `SignColumn` like this.

```vim
:hi SignColumn ctermfg=14 ctermbg=240 guifg=Cyan guibg=#4a5b6c
```

![image](https://user-images.githubusercontent.com/48169/48298484-927a0b80-e501-11e8-9564-f54946d08904.png)

How do you think?

**Comment by rhysd** [comment]
うーん，非公式な機能には対応しないです．タブサイドバー側での設定を検討してください．ちなみに sign の色はタブやウィンドウセパレータなど，「枠」となるパーツで色を統一するためにあえて同じ色にしています．

**Comment by tyru** [comment]
了解です。 `TabSideBar` グループの色を調整してみることにします。
ありがとうございます。
