### ISSUE TITLE
Spellcheck error is not comfortable to read  

### ISSUE THREAD

**Issue by robsonpeixoto** [rhysd/vim-color-spring-night#9]
The red background is not comfortable.
![image](https://user-images.githubusercontent.com/124390/60171059-32aa4980-97e0-11e9-9457-dfb4e6a66140.png)

My suggestion is use a solution like dracula:
<img width="277" alt="Screen Shot 2019-06-26 at 07 05 32" src="https://user-images.githubusercontent.com/124390/60171430-ffb48580-97e0-11e9-9909-eac065bf78d2.png">

**Comment by rhysd** [comment]
Thank you for reporting this. It should be fixed.

**Comment by rhysd** [comment]
Fixed at 390d874

- Before

<img width="418" alt="before" src="https://user-images.githubusercontent.com/823277/60174254-a03f8f80-984b-11e9-8b69-cff32f742a0f.png">

- After

<img width="418" alt="after" src="https://user-images.githubusercontent.com/823277/60174263-a6357080-984b-11e9-8a68-ae6599c7cb34.png">
